# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install packages
      run: go mod download
      
    - name: Run Balancer Unit Tests
      run: go test -v ./cmd/lb

    - name: Run docker-compose
      run: docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
